---
title: "cities"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(maps)
```


```{r}
acfrs_city_pop_added_char <- readRDS("data/acfrs_city_pop_added_char.RDS")

# Top100 for Jordan to map, rename col to match Jordan's original files 

cities_acfrs_pop_formap <- acfrs_city_pop_added_char %>% 
  rename(entity = name,
         state_abv = state.abb, 
         state = state.name, 
         city = city_town, 
         ) %>% 

  # Fixing some names  
  mutate(city = str_remove(city, " city"), 
         city = str_remove(city, " City")) %>% 
  mutate(city = ifelse(city == "Indianapolis (balance)", "Indianapolis", city)) %>% 
  mutate(city = ifelse(city == "Lexington-Fayette urban county", "Lexington", city)) %>% 
  mutate(city = ifelse(city == "Anchorage municipality", "Anchorage", city)) %>% 
  mutate(city = ifelse(city == "Gilbert town", "Gilbert", city)) %>% 
  
  
  mutate(lib_rev_ratio = (round(total_liabilities/revenues, 4))*100) %>% 
  select(state_abv, state, city, total_liabilities, revenues, lib_rev_ratio, population) %>% arrange(desc(population)) %>% slice(1:100) 


```

```{r}
# getting lat, long from Jordan's file (original file put on github repo gov_fin_al): 
top100_cities_latlong <- read.csv("data/cities_lat_long.csv") %>% select(state_abv, city, lat, long) %>% 
  mutate(city = ifelse(city == "Government of the District of Columbia", "Washington", city),
         city = str_remove(city, " City")) 

# get more lat, long from maps package

cities_lat_long <- us.cities %>% 
  rename(state_abv = country.etc) %>% 
  mutate(city = str_sub(name, 1, -4)) %>% select(state_abv, city, lat, long) %>% 
  filter(state_abv %in% c("CA", "GA", "MA")) %>% 
  filter(str_detect(city, "Fontana|Columbus|Worcester"))

# top 100 cities

cities <- left_join(cities_acfrs_pop_formap, top100_cities_latlong) %>% 
  mutate(lat = ifelse(city == "Fontana", 34.10, lat),
        long = ifelse(city == "Fontana", -117.46, long),
        
        lat = ifelse(city == "Columbus", 32.51, lat),
        long = ifelse(city == "Columbus", -84.87, long),
        
        lat = ifelse(city == "Worcester", 42.27, lat),
        long = ifelse(city == "Worcester", -71.81, long))

```


```{r}

write.csv(cities, "cities.csv")
```



