---
title: "counties"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
```

```{r}
county_pop_census_acfrs <- readRDS("data/county_pop_census_acfrs.RDS")

# To map
counties_1 <- county_pop_census_acfrs %>% 
  mutate(lib_rev_ratio = (total_liabilities/revenues)*100,
         percapita = total_liabilities/population, 
         county = str_to_title(county)) %>% 
  
  #rename cols to match Jordan's original files to display on map
  rename(FIPS = id.y, 
         state_abv = state.abb,  
            state = state.name,
         name = county,
         revenue = revenues
         ) %>%
  
  
  mutate(FIPS = str_sub(FIPS, -5, -1)) %>% 
  arrange(desc(population)) %>% 
  select(FIPS, state, name, population, total_liabilities, revenue, lib_rev_ratio, percapita, state_abv) %>% arrange(desc(population)) 

```

# Special cases: Combined city/ county government
```{r}
# Some cities are counties --> get from list of cities
cities <- read.csv("cities.csv") %>% 
select(-c(lat, long, X)) %>% rename(name = city, # to match with colnames in counties file
                                 revenue = revenues) 

##Jacksonville city, FL  = Duval County, FL # copy the data for Jacksonville city, FL to a new row in the County data for Duval County, FL

jacksonville_duval <- cities %>% 
filter(state_abv == "FL" & name == "Jacksonville") %>% 
mutate(percapita = total_liabilities/population,
 # adding FIPS code manually
      FIPS = "12031", # got it here https://www.census.gov/quickfacts/fact/table/duvalcountyflorida,US/PST045221
      name = ifelse(name == "Jacksonville", "Duval County", name))

## San Francisco city, CA = San Francisco County, CA
sanfrancisco <- cities %>% 
filter(state_abv == "CA" & name == "San Francisco") %>% 
  mutate(percapita = total_liabilities/population, 
         FIPS = "06075",
         name = ifelse(name == "San Francisco", "San Francisco County", name))

```


```{r}
#Denver, CO
denver <- cities  %>% 
filter(state_abv == "CO" & name == "Denver") %>% 
  mutate(percapita = total_liabilities/population, 
         FIPS = "08031", 
         name = ifelse(name == "Denver", "Denver County", name)) 

```


```{r}
#Philadelphia, PA

philadelphia <- cities %>% 
filter(state_abv == "PA" & name == "Philadelphia") %>% 
  mutate(percapita = total_liabilities/population, 
         FIPS = "42101", 
         name = ifelse(name == "Philadelphia", "Philadelphia County", name))
```

```{r}
#Indianapolis-Marion County, Indiana
indianapolis_marion <- cities %>% 
filter(state_abv == "IN" & name == "Indianapolis") %>% 
  mutate(percapita = total_liabilities/population, 
         FIPS = "1836003", # Indianapolis city (balance), Indiana
         name = ifelse(name == "Indianapolis", "Indianapolis-Marion County", ""))
```


```{r}
counties <- rbind(counties_1, 
                  jacksonville_duval, 
                  sanfrancisco,
                  denver,
                  philadelphia,
                  indianapolis_marion) 


#re check all special cases: 
counties  %>% 
  filter(name == "Duval County" |
                      name == "San Francisco County" |
                      name == "Denver County" |
                      name == "Philadelphia County" |
                      name == "Indianapolis-Marion County" |
                      name == "Louisville-Jefferson County" |
                      name == "Nashville-Davidson County"
                      ) %>% 
  filter(state != "Texas")

# check other cases: Kaua‘i County, HI; Dekalb County, AL; Desoto County, FL; St Francis County, AR
counties %>% 
  filter(str_detect(name, "Kauai|Dekalb|Desoto|Francis"))

counties %>% filter(state_abv == "KY" |state_abv == "TN") %>% 
  filter(name == "Jefferson County" | 
           name == "Davidson County")


write.csv(counties, "counties.csv")
```

