---
title: "States Data for Mapping"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
```

# ACFRs data from Database
Object `data_from_dbsite.RDS` is generated from the ACFR PostgreSQL database. 
```{r}
# May 11, 2022
acfrs <- readRDS("data/data_from_dbsite.RDS")


states_47 <- acfrs %>% 
  filter(category == "General Purpose") %>% 
  filter(name != "State of Yap" & name != "State of Kosrae") %>%  # take this out? 
  filter(str_detect(name, "(State of )") | name == "Government of the District of Columbia") %>% 
  mutate(lib_rev_ratio = (total_liabilities/revenues)*100) %>% 
  arrange(name) %>% select(state, name, total_liabilities, revenues, lib_rev_ratio)


# above only give 47 states. Check the differences with list of states                   
states_47 %>% 
  mutate(state_name = str_remove_all(name, "State of ")) -> test
setdiff(test$state_name, state.name)
setdiff(state.name, test$state_name)
```


```{r}
# need to get 4 more: [1] "Kentucky"      "Massachusetts" "Pennsylvania"  "Virginia" 
states_4 <- acfrs %>% 
  filter(category == "General Purpose") %>% 
  filter(str_detect(name, "Commonwealth of")) %>% 
  mutate(lib_rev_ratio = (total_liabilities/revenues)*100) %>% 
  arrange(name) %>% select(state, name, total_liabilities, revenues, lib_rev_ratio)

```


```{r}
# Now have 50 states and DC 
# need to change colnames to be identical with Jordan's original files --> display on map 
states_51 <- rbind(states_47, states_4) %>% select(-state) %>% 
  rename(state = name, 
         revenue = revenues) %>% 

  
  #clean state names to match with those names in census population data 
  mutate(state = str_remove(state, "State of "),
        state = str_remove(state, "Commonwealth of "),
        state = str_remove(state, "Government of the "))
saveRDS(states_51, "states_51.RDS")        
```

# Population data from Census

```{r}
#https://www.census.gov/programs-surveys/popest/technical-documentation/research/evaluation-estimates/2020-evaluation-estimates/2010s-state-detail.html
population <- rio::import("data/states_population2020_census.xlsx", skip = 8) %>% select(1:2) %>% 
  rename(state = West,
         population = "78654756") %>% 
  mutate(state = str_remove(state, ".")) %>% slice(1:51)
```


```{r}
states <- left_join(states_51, population) %>% 
  mutate(per_capita = total_liabilities/population) %>% 
  arrange(state)

write.csv(states, "states.csv")
```

```{r}
library(viridis)
top10_liabilities_rev_ratio <- states %>% arrange(desc(lib_rev_ratio)) %>% slice(1:10)
  top10_liabilities_rev_ratio
  
region <- data.frame(state.name, state.region) %>% rename(state = state.name)


states %>% left_join(region) %>% 
  ggplot(aes(population, lib_rev_ratio)) +
  geom_point(aes(size = population, color = state.region), alpha = .8) +
  
    # add lines 
  geom_hline(yintercept = round(mean(states$lib_rev_ratio)),
             linetype = "dashed", color = "gray", size = .5) +
    annotate(geom = "text", x = 700000, y = 85, label = paste("Mean = ", round(mean(states$lib_rev_ratio)))) +
  
    
  scale_x_log10() + 
  scale_fill_viridis(discrete=TRUE, guide=FALSE, option="A") +
  #scale_color_viridis(option = "H") +
  labs(
    x = "Population (log scale)",
    y = "Ratios",
    title = "Ratios of Liabilities to Revenue",
    subtitle = "States Government") +
  guides(size = FALSE) +
  theme_minimal() 

  
```




